FROM node:22-alpine 

WORKDIR /app

# Install dependencies 

#Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./


# Install dependencies  
RUN npm install --legacy-peer-deps

# Copy the rest of the application code to the working directory
COPY . .

# Copy the prisma schema and seed files
COPY prisma ./prisma

# Run the Prisma migration
RUN npx prisma generate

# Expose the application port
EXPOSE 3000

# Start the development server
CMD ["npm", "run", "dev"]
