version: '3.8'

services:
   app:
      build:
         context: .
         dockerfile: Dockerfile.dev
      ports:
         - '3000:3000'
      volumes:
         - .:/app
         - /app/node_modules
         - /app/.next
      environment:
         - NODE_ENV=development
           - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      depends_on:
         - postgres
      command: npm run dev
      networks:
         - app-network
   postgres:
      image: postgres:14-alpine
      ports:
         - '5432:5432'
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DB}
      volumes:
         - postgres-data-dev:/var/lib/postgresql/data
      networks:
         - app-network

networks:
   app-network:
      driver: bridge

volumes:
   postgres-data-dev:
