name: Create Pull Request from Develop to Main

on:
   workflow_run:
      workflows: ['CI/CD Pipeline']
      types:
         - completed

jobs:
   create-pull-request:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repo
           uses: actions/checkout@v4

         - name: Install GitHub CLI
           run: |
              sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
              curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
              sudo apt-add-repository https://cli.github.com/packages
              sudo apt update
              sudo apt install gh -y

         - name: Authenticate GitHub CLI
           run: |
              echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

         - name: Check if PR exists
           id: check_pr
           run: |
              gh pr list --base main --head develop --json number -q ".[].number" > pr.json
              if [ "$(cat pr.json)" = "" ]; then
                echo "create_pr=true" >> $GITHUB_OUTPUT
              else
                echo "create_pr=false" >> $GITHUB_OUTPUT
              fi

         - name: Create pull request
           if: steps.check_pr.outputs.create_pr == 'true'
           uses: devops-infra/action-pull-request@v0.5.3
           with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              source_branch: develop
              target_branch: main
              title: 'Auto PR: Merge develop into main'
              body: |
                 This pull request was automatically created after successful CI/CD run on the develop branch.
                 Please review and merge manually.
              draft: false
              allow_no_diff: true
